from pydantic import ValidationError
from software_whitelisting_assistant.scripts.classes import Tool, TOC
from software_whitelisting_assistant.scripts.llm_client import call_llm
from software_whitelisting_assistant.scripts.artifacts_store import load_prompt


def generate_TOC(
    tool: Tool, 
    document_type: str, 
    prompt_name: str, 
    model: str, 
    temperature: float, 
    max_tokens: int
) -> TOC:
    """
    Generate a table of contents (TOC) for a document using an LLM.

    Args:
        tool (Tool): The tool for which the TOC is generated.
        document_type (str): Type of document to generate (e.g. privacy policy, terms of service).
        prompt_name (str): Name of the prompt template used for TOC generation.
        model (str): Name of the LLM model to use.
        temperature (float): Sampling temperature for generation.
        max_tokens (int): Maximum number of tokens allowed for generation.

    Returns:
        TOC: A validated TOC object generated by the LLM.

    Raises:
        ValidationError: If the LLM output cannot be validated as a TOC.

    Notes:
        If validation fails, the raw LLM response is returned instead.
        Callers should handle this case explicitly.
    """
    prompt = load_prompt(prompt_name).format(
        document_type=document_type,
        tool_name=tool.name,
        purpose=tool.purpose,
        category=tool.category,
        user_base=tool.user_base
    )

    response_text = call_llm(
        prompt=prompt, 
        model=model, 
        temperature=temperature, 
        max_tokens=max_tokens,
        text_format=TOC
    )

    try:
        toc = TOC.model_validate(response_text)
        return toc
    except ValidationError as e:
        print("TOC validation failed:", e)
        return response_text

